export enum SessionActions {
  REGISTER = 'REGISTER',
  LOGIN_STARTED = 'LOGIN_STARTED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  GET_CURRENT_USER = 'GET_CURRENT_USER',

}