export enum SessionActions {
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOGOUT = 'LOGOUT',
  GET_CURRENT_USER = 'GET_CURRENT_USER',
  GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS',
  FIND_SESSION = 'FIND_SESSION',
  NO_SESSION_FOUND = 'NO_SESSION_FOUND',
  SESSION_PERSISTED = 'SESSION_PERSISTED',
}